spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate-knowledge?reWriteBatchedInserts=true
    username: postgres
    password: 12345!fra
    hikari: 
      autoCommit: false    
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 5 # Hibernate will silently disable batch inserts if we use GenerationType.IDENTITY
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        connection.provider_disables_autocommit: true # tells Hibernate that the underlying JDBC Connections already disabled the auto-commit mode.
    show-sql: true
logging.level:
  org.hibernate.type.descriptor.sql: trace
  logger.org.hibernate.SQL: debug
  org.springframework.transaction.interceptor.TransactionAspectSupport: debug